### Send POST request with json body
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "ewapit",
  "password": "szczecin"
}

###
GET http://localhost:8080/api/main/getOrderItems?order_id=1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6ImV3YXBpdCIsImV4cCI6MTY4MjU4NjkzMCwicm9sIjpbIlJPTEVfQURNSU4iLCJST0xFX1ZJRVciLCJST0xFX1dSVCJdfQ.hY8qQXopvJtlane9ywswaujfPldd6iejomyogLmjV4k
###
###
GET http://localhost:8080/api/main/getOrders?order_id=0&customer=ny&order_timestamp=2023-02-02+09:20:45
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6ImV3YXBpdCIsImV4cCI6MTY4MjE2OTAzNSwicm9sIjpbIlJPTEVfQURNSU4iLCJST0xFX1ZJRVciLCJST0xFX1dSVCJdfQ.wvNHamtVeBP6fTgplSKSmIRd15l2D-4wsXdxPRyxJeI
###
###
GET http://localhost:8080/api/main/getCustomers?customer_id=0&cust_last_name=%25
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6ImV3YXBpdCIsImV4cCI6MTY4MTk3NTM0NCwicm9sIjpbIlJPTEVfQURNSU4iLCJST0xFX1ZJRVciLCJST0xFX1dSVCJdfQ.Ao0yDp0CXiNPNeooGeLxyb-kDmnzgWWOfphswcteg2s
###
GET http://localhost:8080/api/main/usrlist?filtrStr=all
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6ImV3YXBpdCIsImV4cCI6MTY3OTY2NDEyMiwicm9sIjpbIlJPTEVfQURNSU4iLCJST0xFX1ZJRVciLCJST0xFX1dSVCJdfQ.pZmPY_12HKcNFNbd9aubaRi5sE-Gf5ZYrs-O6JKY3nA
###
###
GET http://localhost:8080/api/user/usrChgPasswd?username=ewapit&oldpasswd=szczecin&newpasswd=szczecin
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6ImV3YXBpdCIsImV4cCI6MTY3OTcyODYyNSwicm9sIjpbIlJPTEVfQURNSU4iLCJST0xFX1ZJRVciLCJST0xFX1dSVCJdfQ.qKbMxkEGE84uK2FBasv6-p3iJS8pgvaJX83DPEcxsoQ
###
